 docker compose run -e ${ENV} -e ${ENABLE_TEST_RAIL} --entrypoint "dotnet test --settings .runsettings --filter ${TEST_NAME} bin/Debug/netcoreapp3.1/TrxUITest.dll" trxuitest

version: 0.2

phases:
    install:
        commands:
            - echo install
        finally:
            - echo install finally
    pre_build:
        commands:
            - echo pre_build
        finally:
            - echo pre_build finally
    build:
        commands:
            - echo Build started on `date`
            - chmod 777 downloads # For Nightwatch versions > 1.2.2, tests with browser downloads will fail without this.
            #- $(aws ecr get-login --no-include-email --region $AWS_DEFAULT_REGION)
            - docker -v
            - aws ecr get-login-password --region us-east-1 | docker login --username AWS --password-stdin 152303423357.dkr.ecr.us-east-1.amazonaws.com
            - docker images
            - docker-compose run -e captcha=${captcha} -e env=docker${ENV} -e enableTestRail=${enableTestRail} -e groups="${groups}" -e testRunId=${testRunId} -e useRebalanceAPI=${useRebalanceAPI} -T nightwatch
            # - docker build -t trx-ui-test-automation .
            - docker images
            # - docker tag node:10 152303423357.dkr.ecr.us-east-1.amazonaws.com/trx-ui-test-automation:node
            # - docker push 152303423357.dkr.ecr.us-east-1.amazonaws.com/trx-ui-test-automation:node
            # - docker build -t node-chrome-debug .
            # - docker tag selenium/node-chrome-debug:3.141.59-oxygen 152303423357.dkr.ecr.us-east-1.amazonaws.com/trx-ui-test-automation:node-chrome-debug
            # - docker push 152303423357.dkr.ecr.us-east-1.amazonaws.com/trx-ui-test-automation:node-chrome-debug
            # - docker build -t selenium-hub .
            # - docker tag trx-ui-test-automation:selenium-hub 152303423357.dkr.ecr.us-east-1.amazonaws.com/trx-ui-test-automation:selenium-hub
            # - docker push 152303423357.dkr.ecr.us-east-1.amazonaws.com/trx-ui-test-automation:selenium-hub
            - nightwatch_container_id=`docker ps -aql`
            - docker cp ${nightwatch_container_id}:/home/trx-tests/reports .
        finally:
            - echo build finally
    post_build:
        commands:
            - echo Build completed on `date`
reports:
    nightwatch-ui-results:
        files:
            - '**/*'
        base-directory: 'reports'