using NUnit.Framework;
using TestContext = NUnit.Framework.TestContext;
using Ignore = NUnit.Framework.IgnoreAttribute;
using OpenQA.Selenium;
using System.Threading;

namespace TrxUITest.src.utils
{
    public class SubcribeToModels
    {
        [OneTimeSetUp]
        public void OneTimeSetup()
        {
            Test.Startup(GetType().Name);
        }

        [TestCase(0, "default.bak")]
        [Ignore("Only run this to load data, it's not a test")]
        public void TestCase(int testCaseId, string databaseBackupFileName)
        {
            AddOfficeCloudGUId();
            Test.driver.Navigate().GoToUrl("https://trx-uat.morningstar.com/app.aspx#/model-marketplace");
            SeleniumHelpers.FindElement(title);

            int ix = 1;

            foreach (string model in models)
            {
                Subscribe(model, $"subscription.{ix++}");
            }
        }

        [TearDown]
        public void TestCaseTearDown()
        {
            Test.TestCaseFinish();
            Test.LogOut();
            Test.driver.Close();
            //Database.Cleanup(Test.dbServer, Test.guid); Save the database to backup, then delete manually.
            ExpectedResults.Close(Test.generateExpectedResults);
        }

        [OneTimeTearDown]
        public void OneTimeTearDown()
        {
            TestContext.Progress.WriteLine("OneTimeTearDown");
        }

        public void Subscribe(string marketplaceModel, string newModel)
        {
            IWebElement filter = SeleniumHelpers.FindElement(modelFilter);
            filter.Clear();
            filter.SendKeys(marketplaceModel);
            Thread.Sleep(2000);

            IWebElement subscribeButtonElement = SeleniumHelpers.FindElement(subscribe);
            SeleniumHelpers.WaitForElementToBeVisible(subscribe);
            Thread.Sleep(2000);
            subscribeButtonElement.Click();

            IWebElement modelRename = SeleniumHelpers.FindElement(subscribeRename);
            modelRename.Clear();
            modelRename.SendKeys(newModel);
            Thread.Sleep(2000);

            IWebElement saveButtonElement = SeleniumHelpers.FindElement(subscribeSave);
            SeleniumHelpers.WaitForElementToBeVisible(subscribeSave);
            Thread.Sleep(1000);
            saveButtonElement.Click();
            Thread.Sleep(1000);

            SeleniumHelpers.FindElement(modelNameModalHeader, 300);


            SeleniumHelpers.FindElement(hereLink, 300);
            SeleniumHelpers.WaitForElementToBeVisible(hereLink, 300);

            IWebElement closeButtonElement = SeleniumHelpers.FindElement(subscribeClose);
            Thread.Sleep(2000);
            closeButtonElement.Click();
            SeleniumHelpers.WaitForElementToDisappear(spinner);
            Thread.Sleep(1000);
        }

        public void AddOfficeCloudGUId()
        {
            string query = $"update TrxConfig.dbo.Users set OfficeCloudId='cc45f799-d031-45f1-8dc0-12718ce7a108' where Login='{Test.trxUserName}'";
            Database.RunQuery(Test.dbServer, query);
        }

        public static string title = "#bread-crumb-title";
        public static string modelFilter = "#models-grid-filter-Name";
        public static string model = "#models-grid > div > div.tg-pane-bodyer > div.tg-scrollpane.tg-pane.tg-pane-top.tg-pane-left.tg-pane-top-left > div > div > div.tg-row.tg-level-0.tg-even.tg-pane-first.tg-list-first > div.tg-cell.tg-c-1.tg-level-0.tg-align-left";
        public static string subscribe = "#models-grid > div > div.tg-pane-bodyer > div.tg-scrollpane.tg-pane.tg-pane-top.tg-pane-left.tg-pane-top-left > div > div > div.tg-row.tg-level-0.tg-even.tg-pane-first.tg-list-first > div.tg-cell.tg-c-3.tg-level-0.tg-align-left > button";
        public static string subscribeSave = "#save-models-btn";
        public static string subscribeClose = "#close-model-btn";
        public static string subscribeRename = "#model-name-modal .mds-form__input";
        public static string spinner = "#edge > div > div > div.loader-overlay > div > div";
        public static string hereLink = "#model-name-modal > div.mds-modal__wrapper > section > div > div > div:nth-child(1) > p:nth-child(2) > b > span";
        public static string modelNameModalHeader = "#model-name-modal-header";

        public static string[] models = {
            "American Funds Conservative Growth and Income Model F2",
            "American Funds Conservative Growth and Income Model F3",
            "American Funds Conservative Income Model F2",
            "American Funds Conservative Income Model F3",
            "American Funds Global Growth Model Portfolio F2",
            "American Funds Global Growth Model Portfolio F3",
            "American Funds Growth and Income Model Portfolio F2",
            "American Funds Growth and Income Model Portfolio F3",
            "American Funds Growth Model Portfolio F2",
            "American Funds Growth Model Portfolio F3",
            "American Funds Moderate Growth and Income Model Portfolio F2",
            "American Funds Moderate Growth and Income Model Portfolio F3",
            "American Funds Moderate Growth Model Portfolio F2",
            "American Funds Moderate Growth Model Portfolio F3",
            "American Funds Preservation Model Portfolio F2",
            "American Funds Preservation Model Portfolio F3",
            "American Funds Retirement Income Model - Conservative F2",
            "American Funds Retirement Income Model - Conservative F3",
            "American Funds Retirement Income Model - Enhanced F2",
            "American Funds Retirement Income Model - Enhanced F3",
            "American Funds Retirement Income Model - Moderate F2",
            "American Funds Retirement Income Model - Moderate F3",
            "American Funds Tax-Aware Conservative Growth and Income F2",
            "American Funds Tax-Aware Conservative Growth and Income F3",
            "American Funds Tax-Aware Conservative Inc F2",
            "American Funds Tax-Aware Conservative Inc F3",
            "American Funds Tax-Aware Growth and Income F2",
            "American Funds Tax-Aware Growth and Income F3",
            "American Funds Tax-Aware Moderate Growth and Income F2",
            "American Funds Tax-Aware Moderate Growth and Income F3",
            "American Funds Tax-Aware Moderate Income F2",
            "American Funds Tax-Aware Moderate Income F3",
            "American Funds Tax-Exempt Preservation Model Portfolio F2",
            "American Funds Tax-Exempt Preservation Model Portfolio F3",
            "AQR Diversifying Strategies Model Portfolio",
            "BlackRock Global Allocation Selects 100/0",
            "BlackRock Global Allocation Selects 20/80",
            "BlackRock Global Allocation Selects 40/60",
            "BlackRock Global Allocation Selects 60/40",
            "BlackRock Global Allocation Selects Tax Aware 20/80",
            "BlackRock Global Allocation Selects Tax Aware 40/60",
            "BlackRock Global Allocation Selects Tax Aware 60/40",
            "BlackRock Global Allocation Selects Tax Aware 80/20",
            "BlackRock Global Allocations Selects 80/20",
            "BlackRock Long Hoirzon Mutual Fund 100/0",
            "BlackRock Long Horizon Mutual Fund 20/80",
            "BlackRock Long Horizon Mutual Fund 40/60",
            "BlackRock Long Horizon Mutual Fund 60/40",
            "BlackRock Long Horizon Mutual Fund 80/20",
            "BlackRock Multi-Asset Income MF/ETF - Conservative Index",
            "BlackRock Multi-Asset Income MF/ETF - Moderate Growth Index",
            "BlackRock Multi-Asset Income MF/ETF - Moderate Index",
            "BlackRock Multi-Asset Income Tax-Aware MF/ETF - Conservative Index",
            "BlackRock Multi-Asset Income Tax-Aware MF/ETF - Moderate Growth Index",
            "BlackRock Multi-Asset Income Tax-Aware MF/ETF - Moderate Index",
            "BlackRock Target Allocation 0/100 ETF",
            "BlackRock Target Allocation 10/90 ETF",
            "BlackRock Target Allocation 100/0 ETF",
            "BlackRock Target Allocation 20/80 ETF",
            "BlackRock Target Allocation 30/70 ETF",
            "BlackRock Target Allocation 40/60 ETF",
            "BlackRock Target Allocation 50/50 ETF",
            "BlackRock Target Allocation 60/40 ETF",
            "BlackRock Target Allocation 70/30 ETF",
            "BlackRock Target Allocation 80/20 ETF",
            "BlackRock Target Allocation 90/10 ETF",
            "BlackRock Target Allocation ESG 40/60",
            "BlackRock Target Allocation ESG 60/40",
            "BlackRock Target Allocation ESG 80/20",
            "BlackRock Target Allocation ESG Equity",
            "BlackRock Target Allocation MM w Alts 20/80",
            "BlackRock Target Allocation MM w Alts 40/60",
            "BlackRock Target Allocation MM w Alts 60/40",
            "BlackRock Target Allocation MM w Alts 80/20",
            "BlackRock Target Allocation MM w Alts Equity",
            "BlackRock Target Allocation MM w Alts Tax Aware 20/80",
            "BlackRock Target Allocation MM w Alts Tax Aware 40/60",
            "BlackRock Target Allocation MM w Alts Tax Aware 60/40",
            "BlackRock Target Allocation MM w Alts Tax Aware 80/20",
            "BlackRock Target Allocation MM w Alts Tax Aware Equity",
            "BlackRock Target Allocation Multi-Manager 0/100",
            "BlackRock Target Allocation Multi-Manager 10/90",
            "BlackRock Target Allocation Multi-Manager 100/0",
            "BlackRock Target Allocation Multi-Manager 20/80",
            "BlackRock Target Allocation Multi-Manager 30/70",
            "BlackRock Target Allocation Multi-Manager 40/60",
            "BlackRock Target Allocation Multi-Manager 50/50",
            "BlackRock Target Allocation Multi-Manager 60/40",
            "BlackRock Target Allocation Multi-Manager 70/30",
            "BlackRock Target Allocation Multi-Manager 80/20",
            "BlackRock Target Allocation Multi-Manager 90/10",
            "BlackRock Target Allocation Smart Beta 100/0",
            "BlackRock Target Allocation Smart Beta 40/60",
            "BlackRock Target Allocation Smart Beta 60/40",
            "BlackRock Target Allocation Smart Beta 80/20",
            "BlackRock Target Allocation Tax Aware ETF 0/100",
            "BlackRock Target Allocation Tax Aware ETF 10/90",
            "BlackRock Target Allocation Tax Aware ETF 100/0",
            "BlackRock Target Allocation Tax Aware ETF 20/80",
            "BlackRock Target Allocation Tax Aware ETF 30/70",
            "BlackRock Target Allocation Tax Aware ETF 40/60",
            "BlackRock Target Allocation Tax Aware ETF 50/50",
            "BlackRock Target Allocation Tax Aware ETF 60/40",
            "BlackRock Target Allocation Tax Aware ETF 70/30",
            "BlackRock Target Allocation Tax Aware ETF 80/20",
            "BlackRock Target Allocation Tax Aware ETF 90/10",
            "BlackRock Target Income ETF Aggressive",
            "BlackRock Target Income ETF Core",
            "BlackRock Target Income ETF High",
            "BlackRock Target Income ETF Moderate",
            "Bull Bear",
            "Calvert Responsible Allocation Aggressive Growth Model",
            "Calvert Responsible Allocation Conservative Model",
            "Calvert Responsible Allocation Growth Model",
            "Calvert Responsible Allocation Income with Capital Preservation Model",
            "Calvert Responsible Allocation Moderate Model",
            "DSP - Growth with Income",
            "DSP - Growth with Income (Tax Sensitive)",
            "DSP - Growth with Mod Income",
            "DSP - Growth with Mod Income (Tax Sensitive)",
            "DSP - Income",
            "DSP - Income (Tax Sensitive)",
            "DSP - Income with Mod Growth",
            "DSP - Income with Mod Growth (Tax Sensitive)",
            "DSP - Maximum Growth",
            "DSP - Maximum Growth (Tax Sensitive)",
            "Fidelity Bond Income (I) Model Portfolio",
            "Fidelity Bond Income (Z) Model Portfolio",
            "Fidelity Core Bond (I) Model Portfolio",
            "Fidelity Core Bond (Z) Model Portfolio",
            "Fidelity Core Plus Bond (I) Model Portfolio",
            "Fidelity Core Plus Bond (Z) Model Portfolio",
            "Fidelity Dynamic Bond (I) Model Portfolio",
            "Fidelity Dynamic Bond (Z) Model Portfolio",
            "Fidelity Multi-Asset Business Cycle (I) Model Portfolio",
            "Fidelity Multi-Asset Business Cycle (Z) Model Portfolio",
            "Fidelity Multi-Asset Income (I) Model Portfolio",
            "Fidelity Multi-Asset Income (Z) Model Portfolio",
            "Fidelity Sector Equity Business Cycle (I) Model Portfolio",
            "Fidelity Sector Equity Business Cycle (Z) Model Portfolio",
            "Fidelity Short Multi-Sector Bond (I) Model Portfolio",
            "Fidelity Short Multi-Sector Bond (Z) Model Portfolio",
            "Fidelity Target Allocation 20/80 (I) Model Portfolio",
            "Fidelity Target Allocation 20/80 (Z) Model Portfolio",
            "Fidelity Target Allocation 40/60 (I) Model Portfolio",
            "Fidelity Target Allocation 40/60 (Z) Model Portfolio",
            "Fidelity Target Allocation 60/40 (I) Model Portfolio",
            "Fidelity Target Allocation 60/40 (Z) Model Portfolio",
            "Fidelity Target Allocation 70/30 (I) Model Portfolio",
            "Fidelity Target Allocation 70/30 (Z) Model Portfolio",
            "Fidelity Target Allocation 85/15 (I) Model Portfolio",
            "Fidelity Target Allocation 85/15 (Z) Model Portfolio",
            "Fidelity Target Allocation Index-Focused 20/80 Model Portfolio",
            "Fidelity Target Allocation Index-Focused 40/60 Model Portfolio",
            "Fidelity Target Allocation Index-Focused 60/40 Model Portfolio",
            "Fidelity Target Allocation Index-Focused 70/30 Model Portfolio",
            "Fidelity Target Allocation Index-Focused 85/15 Model Portfolio",
            "Fidelity U.S. Equity Defensive Factor ETF Model Portfolio",
            "Fidelity U.S. Equity Factor ETF Model Portfolio",
            "Fidelity U.S. Equity Income Factor ETF Model Portfolio",
            "Franklin Templeton Conservative Growth",
            "Franklin Templeton Equity Growth",
            "Franklin Templeton Growth",
            "Franklin Templeton Growth & Enhanced Income",
            "Franklin Templeton Growth & Income",
            "Franklin Templeton Income",
            "Franklin Templeton Moderate Growth",
            "Franklin Templeton Rising Rates Defense",
            "Franklin Templeton Stability",
            "Franklin Templeton Tax-Advantaged Growth & Income",
            "Franklin Templeton Tax-Advantaged Income",
            "Franklin Templeton Tax-Advantaged Stability",
            "Global X China Sector ETF Model Portfolio",
            "Global X Core Series Aggressive ETF Model Portfolio",
            "Global X Core Series Conservative  ETF Model Portfolio",
            "Global X Core Series Moderate ETF Model Portfolio",
            "Global X Core Series Moderately Aggressive ETF Model Portfolio",
            "Global X Core Series Moderately Conservative  ETF Model Portfolio",
            "Global X Digital Innovation ETF Model Portfolio",
            "Global X Equity Income ETF Model Portfolio",
            "Global X Equity Sector and Themes ETF Model Portfolio",
            "Global X Equity Thematic Disruptors ETF Model Portfolio",
            "Global X Sustainable Core Series Aggressive ETF Model Portfolio",
            "Global X Sustainable Core Series Moderate ETF Model Portfolio",
            "Goal Engineer - 2015",
            "Goal Engineer - 2020",
            "Goal Engineer - 2025",
            "Goal Engineer - 2030",
            "Goal Engineer - 2035",
            "Goal Engineer - 2040",
            "Goal Engineer - Stable Income",
            "Guardian",
            "Income Plus",
            "Invesco Cornerstone Series: Total Beta 20 Portfolio",
            "Invesco Cornerstone Series: Total Beta 30 Portfolio",
            "Invesco Cornerstone Series: Total Beta 40 Portfolio",
            "Invesco Cornerstone Series: Total Beta 50 Portfolio",
            "Invesco Cornerstone Series: Total Beta 60 Portfolio",
            "Invesco Cornerstone Series: Total Beta 70 Portfolio",
            "Invesco Cornerstone Series: Total Beta 80 Portfolio",
            "Invesco International Diversification Blend Portfolio",
            "Invesco International Diversification Equity Portfolio",
            "Invesco Pinnacle Series: Hybrid Plus 20 MM Portfolio",
            "Invesco Pinnacle Series: Hybrid Plus 40 MM Portfolio",
            "Invesco Pinnacle Series: Hybrid Plus 60 MM Portfolio",
            "Invesco Pinnacle Series: Hybrid Plus 80 MM Portfolio",
            "Invesco Pinnacle Series: Hybrid Plus Equity MM Portfolio",
            "Invesco Pinnacle Series: MF Plus 20 Portfolio",
            "Invesco Pinnacle Series: MF Plus 40 Portfolio",
            "Invesco Pinnacle Series: MF Plus 60 Portfolio",
            "Invesco Pinnacle Series: MF Plus 80 Portfolio",
            "Invesco Pinnacle Series: MF Plus Equity Portfolio",
            "Invesco Pinnacle Series: Smart Beta 10 Portfolio",
            "Invesco Pinnacle Series: Smart Beta 20 Portfolio",
            "Invesco Pinnacle Series: Smart Beta 30 Portfolio",
            "Invesco Pinnacle Series: Smart Beta 40 Portfolio",
            "Invesco Pinnacle Series: Smart Beta 50 Portfolio",
            "Invesco Pinnacle Series: Smart Beta 60 Portfolio",
            "Invesco Pinnacle Series: Smart Beta 70 Portfolio",
            "Invesco Pinnacle Series: Smart Beta 80 Portfolio",
            "Invesco Pinnacle Series: Smart Beta 90 Portfolio",
            "Invesco Pinnacle Series: Smart Beta Equity Portfolio",
            "Invesco Pinnacle Series: Smart Beta Income Portfolio",
            "Invesco Pinnacle Series: Total Beta 10 MM Portfolio",
            "Invesco Pinnacle Series: Total Beta 20 MM Portfolio",
            "Invesco Pinnacle Series: Total Beta 30 MM Portfolio",
            "Invesco Pinnacle Series: Total Beta 40 MM Portfolio",
            "Invesco Pinnacle Series: Total Beta 50 MM Portfolio",
            "Invesco Pinnacle Series: Total Beta 60 MM Portfolio",
            "Invesco Pinnacle Series: Total Beta 70 MM Portfolio",
            "Invesco Pinnacle Series: Total Beta 80 MM Portfolio",
            "Invesco Pinnacle Series: Total Beta 90 MM Portfolio",
            "Invesco Pinnacle Series: Total Beta Equity MM Portfolio",
            "Invesco Pinnacle Series: Total Beta Income MM Portfolio",
            "Invesco U.S. Factor Rotation Portfolio",
            "John Hancock Global Dynamic Equity Model Portfolio",
            "John Hancock Multi Asset Income Model Portfolio",
            "John Hancock Multimanager Active/Passive Aggressive Model Portfolio",
            "John Hancock Multimanager Active/Passive Balanced Model Portfolio",
            "John Hancock Multimanager Active/Passive Conservative Model Portfolio",
            "John Hancock Multimanager Active/Passive Growth Model Portfolio",
            "John Hancock Multimanager Active/Passive Moderate Model Portfolio",
            "John Hancock Multimanager Aggressive Model Portfolio",
            "John Hancock Multimanager Balanced Model Portfolio",
            "John Hancock Multimanager Conservative Model Portfolio",
            "John Hancock Multimanager Growth Model Portfolio",
            "John Hancock Multimanager Moderate Model Portfolio",
            "JPM Morningstar ETF Aggressive",
            "JPM Morningstar ETF Balanced",
            "JPM Morningstar ETF Conservative",
            "JPM Morningstar ETF Growth",
            "JPM Morningstar ETF Stable",
            "Morningstar Large Core Index",
            "Navigrowth",
            "PGIM Model Portfolios: Aggressive Allocation Portfolio",
            "PGIM Model Portfolios: Balanced Allocation Portfolio",
            "PGIM Model Portfolios: Capital Growth Allocation Portfolio",
            "PGIM Model Portfolios: Defensive Allocation Portfolio",
            "PGIM Model Portfolios: Income Allocation Portfolio",
            "PGIM Model Portfolios: Preservation Allocation Portfolio",
            "PIMCO Retirement Income Model - Balanced",
            "PIMCO Retirement Income Model Cnsrv",
            "PIMCO Retirement Income Model-Mod Gr",
            "PIMCO Tax Aware Fixed Income - Capital Preservation",
            "PIMCO Tax Aware Fixed Income - Enhanced Core",
            "PIMCO Tax Aware Fixed Income - Income Focus",
            "PIMCO Taxable Fixed Income - Capital Preservation",
            "PIMCO Taxable Fixed Income - Enhanced Core",
            "PIMCO Taxable Fixed Income - Income Focus",
            "Putnam Aggressive Growth Model",
            "Putnam Balanced Growth Model",
            "Putnam Balanced Income Model",
            "Putnam Conservative Growth Model",
            "Putnam Growth Model",
            "Putnam Income Model",
            "Redwood Engineered Risk Budget: 05-08% Drawdown Target",
            "Redwood Engineered Risk Budget: 08-12% Drawdown Target",
            "Redwood Engineered Risk Budget: 12-17% Drawdown Target",
            "Redwood Engineered Risk Budget: 17-25% Drawdown Target",
            "Redwood Engineered Risk Budget: 25%+ Drawdown Target",
            "Russell Investments Balanced",
            "Russell Investments Balanced Growth",
            "Russell Investments Balanced Income",
            "Russell Investments Conservative",
            "Russell Investments Conservative Income",
            "Russell Investments Equity Growth",
            "Russell Investments Growth",
            "Russell Investments Hybrid Balanced",
            "Russell Investments Hybrid Balanced Growth",
            "Russell Investments Hybrid Conservative",
            "Russell Investments Hybrid Equity Growth",
            "Russell Investments Hybrid Growth",
            "Russell Investments Hybrid Moderate",
            "Russell Investments Hybrid Moderate Growth",
            "Russell Investments Moderate",
            "Russell Investments Moderate Growth",
            "Russell Investments Tax-Managed Balanced",
            "Russell Investments Tax-Managed Balanced Growth",
            "Russell Investments Tax-Managed Conservative",
            "Russell Investments Tax-Managed Equity Growth",
            "Russell Investments Tax-Managed Growth",
            "Russell Investments Tax-Managed Moderate",
            "Russell Investments Tax-Managed Moderate Growth",
            "Siegel-WisdomTree Global Equity Model",
            "Siegel-WisdomTree Longevity Model",
            "Structural Alpha 20/80",
            "Structural Alpha 40/60",
            "Structural Alpha 60/40",
            "Structural Alpha 80/20",
            "Symmetry Panoramic 0-100",
            "Symmetry Panoramic 100-0",
            "Symmetry Panoramic 10-90",
            "Symmetry Panoramic 20-80",
            "Symmetry Panoramic 30-70",
            "Symmetry Panoramic 40-60",
            "Symmetry Panoramic 50-50",
            "Symmetry Panoramic 60-40",
            "Symmetry Panoramic 70-30",
            "Symmetry Panoramic 80-20",
            "Symmetry Panoramic 90-10",
            "Symmetry Panoramic Tax Managed 0-100",
            "Symmetry Panoramic Tax Managed 100-0",
            "Symmetry Panoramic Tax Managed 10-90",
            "Symmetry Panoramic Tax Managed 20-80",
            "Symmetry Panoramic Tax Managed 30-70",
            "Symmetry Panoramic Tax Managed 40-60",
            "Symmetry Panoramic Tax Managed 50-50",
            "Symmetry Panoramic Tax Managed 60-40",
            "Symmetry Panoramic Tax Managed 70-30",
            "Symmetry Panoramic Tax Managed 80-20",
            "Symmetry Panoramic Tax Managed 90-10",
            "T. Rowe Price 10/90 Active Model Portfolio - I Class",
            "T. Rowe Price 10/90 Active Model Portfolio - Investor Class",
            "T. Rowe Price 100 Equity Active Model Portfolio - I Class",
            "T. Rowe Price 100 Equity Active Model Portfolio - Investor Class",
            "T. Rowe Price 100 Fixed Income Model Portfolio - I Class",
            "T. Rowe Price 100 Fixed Income Model Portfolio - Investor Class",
            "T. Rowe Price 20/80 Active Model Portfolio - I Class",
            "T. Rowe Price 20/80 Active Model Portfolio - Investor Class",
            "T. Rowe Price 40/60 Active Model Portfolio - I Class",
            "T. Rowe Price 40/60 Active Model Portfolio - Investor Class",
            "T. Rowe Price 60/40 Active Model Portfolio - I Class",
            "T. Rowe Price 60/40 Active Model Portfolio - Investor Class",
            "T. Rowe Price 70/30 Active Model Portfolio - I Class",
            "T. Rowe Price 70/30 Active Model Portfolio - Investor Class",
            "T. Rowe Price 80/20 Active Model Portfolio - I Class",
            "T. Rowe Price 80/20 Active Model Portfolio - Investor Class",
            "Toews Conservative Income",
            "Toews Defensive Alpha Balanced",
            "Toews Defensive Alpha Equity",
            "Toews Hedged Balanced",
            "Toews Hedged Balanced Growth",
            "Toews Hedged Balanced Income",
            "Toews Hedged Capital Preservation",
            "Toews Hedged Equity",
            "Toews Hedged Growth",
            "Toews High Income",
            "Toews Managed Risk Blueprint",
            "Toews Moderate Income",
            "VanEck Municipal Allocation Strategy",
            "Vanguard Core 10% Equity/ 90% Fixed Income",
            "Vanguard Core 100% Equity",
            "Vanguard Core 100% Fixed Income",
            "Vanguard Core 20% Equity/ 80% Fixed Income",
            "Vanguard Core 30% Equity/ 70% Fixed Income",
            "Vanguard Core 40% Equity/ 60% Fixed Income",
            "Vanguard Core 50% Equity/ 50% Fixed Income",
            "Vanguard Core 60% Equity/ 40% Fixed Income",
            "Vanguard Core 70% Equity/ 30% Fixed Income",
            "Vanguard Core 80% Equity/ 20% Fixed Income",
            "Vanguard Core 90% Equity/ 10% Fixed Income",
            "Vanguard CRSP 10% Equity/ 90% Fixed Income",
            "Vanguard CRSP 100% Equity",
            "Vanguard CRSP 100% Fixed Income",
            "Vanguard CRSP 20% Equity/ 80% Fixed Income",
            "Vanguard CRSP 30% Equity/ 70% Fixed Income",
            "Vanguard CRSP 40% Equity/ 60% Fixed Income",
            "Vanguard CRSP 50% Equity/ 50% Fixed Income",
            "Vanguard CRSP 60% Equity/ 40% Fixed Income",
            "Vanguard CRSP 70% Equity/ 30% Fixed Income",
            "Vanguard CRSP 80% Equity/ 20% Fixed Income",
            "Vanguard CRSP 90% Equity/ 10% Fixed Income",
            "Vanguard Income 10% Equity/ 90% Fixed Income",
            "Vanguard Income 100% Equity",
            "Vanguard Income 100% Fixed Income",
            "Vanguard Income 20% Equity/ 80% Fixed Income",
            "Vanguard Income 30% Equity/ 70% Fixed Income",
            "Vanguard Income 40% Equity/ 60% Fixed Income",
            "Vanguard Income 50% Equity/ 50% Fixed Income",
            "Vanguard Income 60% Equity/ 40% Fixed Income",
            "Vanguard Income 70% Equity/ 30% Fixed Income",
            "Vanguard Income 80% Equity/ 20% Fixed Income",
            "Vanguard Income 90% Equity/ 10% Fixed Income",
            "Vanguard Russell 10% Equity/ 90% Fixed Income",
            "Vanguard Russell 100% Equity",
            "Vanguard Russell 100% Fixed Income",
            "Vanguard Russell 20% Equity/ 80% Fixed Income",
            "Vanguard Russell 30% Equity/ 70% Fixed Income",
            "Vanguard Russell 40% Equity/ 60% Fixed Income",
            "Vanguard Russell 50% Equity/ 50% Fixed Income",
            "Vanguard Russell 60% Equity/ 40% Fixed Income",
            "Vanguard Russell 70% Equity/ 30% Fixed Income",
            "Vanguard Russell 80% Equity/ 20% Fixed Income",
            "Vanguard Russell 90% Equity/ 10% Fixed Income",
            "Vanguard S&P 10% Equity/ 90% Fixed Income",
            "Vanguard S&P 100% Equity",
            "Vanguard S&P 100% Fixed Income",
            "Vanguard S&P 20% Equity/ 80% Fixed Income",
            "Vanguard S&P 30% Equity/ 70% Fixed Income",
            "Vanguard S&P 40% Equity/ 60% Fixed Income",
            "Vanguard S&P 50% Equity/ 50% Fixed Income",
            "Vanguard S&P 60% Equity/ 40% Fixed Income",
            "Vanguard S&P 70% Equity/ 30% Fixed Income",
            "Vanguard S&P 80% Equity/ 20% Fixed Income",
            "Vanguard S&P 90% Equity/ 10% Fixed Income",
            "Vanguard Tax-Efficient 10% Equity/ 90% Fixed Income",
            "Vanguard Tax-Efficient 20% Equity/ 80% Fixed Income",
            "Vanguard Tax-Efficient 30% Equity/ 70% Fixed Income",
            "Vanguard Tax-Efficient 40% Equity/ 60% Fixed Income",
            "Vanguard Tax-Efficient 50% Equity/ 50% Fixed Income",
            "Vanguard Tax-Efficient 60% Equity/ 40% Fixed Income",
            "Vanguard Tax-Efficient 70% Equity/ 30% Fixed Income",
            "Vanguard Tax-Efficient 80% Equity/ 20% Fixed Income",
            "Vanguard Tax-Efficient 90% Equity/ 10% Fixed Income",
            "Wilshire Premier Allocation - Aggressive Growth",
            "Wilshire Premier Allocation - Conservative",
            "Wilshire Premier Allocation - Conservative Tax Sensitive",
            "Wilshire Premier Allocation - Growth",
            "Wilshire Premier Allocation - Growth Tax Sensitive",
            "Wilshire Premier Allocation - Moderate",
            "Wilshire Premier Allocation - Moderate Conservative",
            "Wilshire Premier Allocation - Moderate Conservative Tax Sensitive",
            "Wilshire Premier Allocation - Moderate Growth",
            "Wilshire Premier Allocation - Moderate Growth Tax Sensitive",
            "Wilshire Premier Allocation - Moderate Tax Sensitive",
            "WisdomTree Aggressive Model Portfolio",
            "WisdomTree Conservative Model Portfolio",
            "WisdomTree Core Equity Model Portfolio",
            "WisdomTree Endowment Moderately Aggressive Model Portfolio",
            "WisdomTree Fixed Income Model Portfolio",
            "WisdomTree Global Dividend Model Portfolio",
            "WisdomTree Global Multi-Asset Income Aggressive Model Portfolio",
            "WisdomTree Global Multi-Asset Income Conservative Model Portfolio",
            "WisdomTree Global Multi-Asset Income Moderate Model Portfolio",
            "WisdomTree Moderate Model Portfolio",
            "WisdomTree U.S. Aggressive Growth Model Portfolio",
            "WisdomTree U.S. Moderate Growth Model Portfolio",
            "WisdomTree Volatility Management Portfolio"
        };
    }
}